apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7zf8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eqsb-tenant/rhtap-demo-app/hacbs-test-project-7zf8@sha256:aeb4aba74acf1a6410f8799c7adb374751ffb782694881eb94c5acf61b940973
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
